name: oppgave 17 🚀
on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:
  
defaults:
  run:
    shell: pwsh

jobs:
  blackjack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v4.5
      with:
        modules-to-cache: Az.Storage, Az.Functions, Az.Websites, Az.Resources, Az.Accounts
        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Deploy with Az
      run: ./src/funcApp/deployWithAz.ps1
