name: oppgave 17 🚀
on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:
  
defaults:
  run:
    shell: pwsh

jobs:
  blackjack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Deploy with Bicep
      run: ./src/funcApp/deployWithBicep.ps1
